development:
  # adapter: async
  adapter: postgresql

test:
  adapter: postgresql

production:
  adapter: postgresql
  # adapter: redis
  # url: redis://localhost:6379/1
  # channel_prefix: weixin_bot_webui_production
